export const REQUEST_CREATE_USER = 'REQUEST_CREATE_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const CREATE_USER_FAIL = 'CREATE_USER_FAIL';
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL';

export const GET_CUSTOMER_ID_SUCCESS = 'GET_CUSTOMER_ID_SUCCESS';
export const GET_CUSTOMER_ID_FAIL = 'GET_CUSTOMER_ID_FAIL';

export const GET_CUSTOMER_FAIL = 'GET_CUSTOMER_FAIL';
export const GET_CUSTOMER_SUCCESS = 'GET_CUSTOMER_SUCCESS';

export const KEYCHAIN_FETCH_CREDS_FAIL = 'KEYCHAIN_FETCH_CREDS_FAIL';

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const LOGIN_USER_BEGIN = 'LOGIN_USER_BEGIN';
export const LOGIN_SOCIAL_USER_BEGIN = 'LOGIN_SOCIAL_USER_BEGIN';
export const LOGIN_USER_FINISH = 'LOGIN_USER_FINISH';
export const LOGIN_USER_RESET = 'LOGIN_USER_RESET';

export const PRE_AUTH_PROJECT_DATA = 'PRE_AUTH_PROJECT_DATA';

export const SIGN_USER_OUT = 'SIGN_USER_OUT';

export const AUTH_STATUS_UNKNOWN = 'AUTH_STATUS_UNKNOWN';
export const AUTH_STATUS_ANONYMOUS = 'AUTH_STATUS_ANONYMOUS';
export const AUTH_STATUS_AUTHENTICATED = 'AUTH_STATUS_AUTHENTICATED';

export const UPDATE_SIGNUP_ERROR = 'UPDATE_SIGNUP_ERROR';

export const UPDATE_DEVICE_TOKEN = 'UPDATE_DEVICE_TOKEN';

export const GET_CUSTOMER_REP_SUCCESS = 'GET_CUSTOMER_REP_SUCCESS';
export const GET_CUSTOMER_REP_FAIL = 'GET_CUSTOMER_REP_FAIL';

export const GET_CUSTOMER_REWARDS_TIER = 'GET_CUSTOMER_REWARDS_TIER';

export const SET_IMPERSONATOR_ID = 'SET_IMPERSONATOR_ID';
export const HAS_LOGGED_IN_ON_DEVICE = 'HAS_LOGGED_IN_ON_DEVICE';
