'use strict';

const constants = {
	SITE_ID: '82',
	STORE_ID: '248',

	BANNER_VISIBLE_TIMEOUT: 3000,
	BANNER_SLIDE_DOWN: 700,
	BANNER_SLIDE_UP: 800,

	GET_CUSTOMER_ID_SUCCESS: 'GET_CUSTOMER_ID_SUCCESS',
	GET_CUSTOMER_ID_FAIL: 'GET_CUSTOMER_ID_FAIL',

	KEYCHAIN_FETCH_CREDS_FAIL: 'KEYCHAIN_FETCH_CREDS_FAIL',

	LOGIN_USER_ERROR: 'LOGIN_USER_ERROR',

	LOAD_EVENTS: 'LOAD_EVENTS',
	GLOBAL_LOAD_EVENTS_SUCCESS: 'GLOBAL_LOAD_EVENTS_SUCCESS',
	GLOBAL_LOAD_EVENTS_ERROR: 'GLOBAL_LOAD_EVENTS_ERROR',

	GLOBAL_LOAD_NEXT_EVENTS_SUCCESS: 'GLOBAL_LOAD_NEXT_EVENTS_SUCCESS',
	GLOBAL_LOAD_NEXT_EVENTS_FAIL: 'GLOBAL_LOAD_NEXT_EVENTS_FAIL',

	GLOBAL_ADD_EVENT_SUCCESS: 'GLOBAL_ADD_EVENT_SUCCESS',
	GLOBAL_ADD_EVENT_ERROR: 'GLOBAL_ADD_EVENT_ERROR',

	GLOBAL_SAVE_COMMENT: 'GLOBAL_SAVE_COMMENT',
	GLOBAL_SAVE_COMMENT_SUCCESS: 'GLOBAL_SAVE_COMMENT_SUCCESS',
	GLOBAL_SAVE_COMMENT_ERROR: 'GLOBAL_SAVE_COMMENT_ERROR',

	PROJECT_LOAD_EVENTS_SUCCESS: 'PROJECT_LOAD_EVENTS_SUCCESS',
	PROJECT_LOAD_EVENTS_ERROR: 'PROJECT_LOAD_EVENTS_ERROR',

	PROJECT_LOAD_NEXT_EVENTS_SUCCESS: 'PROJECT_LOAD_NEXT_EVENTS_SUCCESS',
	PROJECT_LOAD_NEXT_EVENTS_FAIL: 'PROJECT_LOAD_NEXT_EVENTS_FAIL',

	PROJECT_ADD_EVENT: 'PROJECT_ADD_EVENT',
	PROJECT_ADD_EVENT_SUCCESS: 'PROJECT_ADD_EVENT_SUCCESS',
	PROJECT_ADD_EVENT_ERROR: 'PROJECT_ADD_EVENT_ERROR',

	PROJECT_SAVE_COMMENT: 'PROJECT_SAVE_COMMENT',
	PROJECT_SAVE_COMMENT_SUCCESS: 'PROJECT_SAVE_COMMENT_SUCCESS',
	PROJECT_SAVE_COMMENT_ERROR: 'PROJECT_SAVE_COMMENT_ERROR',

	LOAD_PHOTOS_SUCCESS: 'LOAD_PHOTOS_SUCCESS',
	LOAD_PHOTOS_FAIL: 'LOAD_PHOTOS_FAIL',
	LOADING_PHOTOS: 'LOADING_PHOTOS',

	SEND_PROJECT_INVITES: 'SEND_PROJECT_INVITES',
	SEND_PROJECT_INVITES_SUCCESS: 'SEND_PROJECT_INVITES_SUCCESS',
	SEND_PROJECT_INVITES_ERROR: 'SEND_PROJECT_INVITES_ERROR',

	LOAD_TEAM_SUCCESS: 'LOAD_TEAM_SUCCESS',
	LOAD_TEAM_FAIL: 'LOAD_TEAM_FAIL',

	LOAD_INVITEES_SUCCESS: 'LOAD_INVITEES_SUCCESS',
	LOAD_INVITEES_FAIL: 'LOAD_INVITEES_FAIL',

	RESEND_INVITE_BEGIN: 'RESEND_INVITE_BEGIN',
	RESEND_INVITE: 'RESEND_INVITE',
	RESEND_INVITE_SUCCESS: 'RESEND_INVITE_SUCCESS',
	RESEND_INVITE_FAIL: 'RESEND_INVITE_FAIL',
	RESEND_ALL_INVITES_SUCCESS: 'RESEND_ALL_INVITES_SUCCESS',
	RESEND_ALL_INVITES_FAIL: 'RESEND_ALL_INVITES_FAIL',
	IS_RESENDING_INVITES: 'IS_RESENDING_INVITES',

	SAVE_PROJECT_SUCCESS: 'SAVE_PROJECT_SUCCESS',
	SAVE_PROJECT_FAIL: 'SAVE_PROJECT_FAIL',
	UPDATE_PROJECT_SUCCESS: 'UPDATE_PROJECT_SUCCESS',

	CHANGE_PROJECT_STATUS_SUCCESS: 'CHANGE_PROJECT_STATUS_SUCCESS',
	CHANGE_PROJECT_STATUS_FAIL: 'CHANGE_PROJECT_STATUS_FAIL',

	RECEIVE_PROJECTS_SUCCESS: 'RECEIVE_PROJECTS_SUCCESS',
	RECEIVE_PROJECTS_FAIL: 'RECEIVE_PROJECTS_FAIL',
	RECEIVE_SHOPPING_LISTS_SUCCESS: 'RECEIVE_SHOPPING_LISTS_SUCCESS',
	RECEIVE_SHOPPING_LISTS_FOR_PROJECT_SUCCESS: 'RECEIVE_SHOPPING_LISTS_FOR_PROJECT_SUCCESS',
	RECEIVE_SHOPPING_LIST_AGGREGATE_DATA: 'RECEIVE_SHOPPING_LIST_AGGREGATE_DATA',

	REJECT_PROJECT_INVITE: 'REJECT_PROJECT_INVITE',
	REJECT_PROJECT_INVITE_SUCCESS: 'REJECT_PROJECT_INVITE_SUCCESS',
	REJECT_PROJECT_INVITE_FAIL: 'REJECT_PROJECT_INVITE_FAIL',

	DELETE_PROJECT_TEAM_MEMBER: 'DELETE_PROJECT_TEAM_MEMBER',
	DELETE_PROJECT_TEAM_MEMBER_SUCCESS: 'DELETE_PROJECT_TEAM_MEMBER_SUCCESS',
	DELETE_PROJECT_TEAM_MEMBER_FAIL: 'DELETE_PROJECT_TEAM_MEMBER_FAIL',

	GET_CUSTOMER_SUCCESS: 'GET_CUSTOMER_SUCCESS',
	GET_CUSTOMER_FAIL: 'GET_CUSTOMER_FAIL',

	LOAD_SINGLE_EVENT_SUCCESS: 'LOAD_SINGLE_EVENT_SUCCESS',
	LOAD_SINGLE_EVENT_FAIL: 'LOAD_SINGLE_EVENT_FAIL',

	SINGLE_EVENT_SAVE_COMMENT: 'SINGLE_EVENT_SAVE_COMMENT',
	SINGLE_EVENT_SAVE_COMMENT_SUCCESS: 'SINGLE_EVENT_SAVE_COMMENT_SUCCESS',
	SINGLE_EVENT_SAVE_COMMENT_FAIL: 'SINGLE_EVENT_SAVE_COMMENT_FAIL',

	LOAD_DEVICE_PHOTOS_SUCCESS: 'LOAD_DEVICE_PHOTOS_SUCCESS',
	LOAD_DEVICE_PHOTOS_FAIL: 'LOAD_DEVICE_PHOTOS_FAIL',

	GET_NOTIFICATION_SETTINGS_SUCCESS: 'GET_NOTIFICATION_SETTINGS_SUCCESS',
	GET_NOTIFICATION_SETTINGS_FAIL: 'GET_NOTIFICATION_SETTINGS_FAIL',

	SAVE_NOTIFICATION_SETTINGS: 'SAVE_NOTIFICATION_SETTINGS',
	SAVE_NOTIFICATION_SETTINGS_SUCCESS: 'SAVE_NOTIFICATION_SETTINGS_SUCCESS',
	SAVE_NOTIFICATION_SETTINGS_FAIL: 'SAVE_NOTIFICATION_SETTINGS_FAIL',

	SOCIAL_LOGIN_PROMPT_CREDS: 'SOCIAL_LOGIN_PROMPT_CREDS',
	SOCIAL_GET_CLIENT_DATA: 'SOCIAL_GET_CLIENT_DATA',
	SOCIAL_LINK_USER: 'SOCIAL_LINK_USER',
	SOCIAL_LINK_USER_ERROR: 'SOCIAL_LINK_USER_ERROR',
	DID_LOGIN_WITH_SOCIAL: 'DID_LOGIN_WITH_SOCIAL',
	DID_OPEN_PREVIOUSLY: 'DID_OPEN_PREVIOUSLY',
	SOCIAL_LOGIN_TYPE: 'SOCIAL_LOGIN_TYPE',
	TOGGLE_PHOTO_SELECTED: 'TOGGLE_PHOTO_SELECTED',

	UPDATE_SIGNUP_ERROR: 'UPDATE_SIGNUP_ERROR',

	SHOULD_PRESENT_NO_EMAIL_ERROR_MESSAGE: 'SHOULD_PRESENT_NO_EMAIL_ERROR_MESSAGE',

	// data manipulation status
	DELETE_PENDING: 'DELETE_PENDING',
	DELETE_FAIL: 'DELETE_FAIL',

	ADD_PENDING: 'ADD_PENDING',
	ADD_FAIL: 'ADD_FAIL',

	UPDATE_PENDING: 'UPDATE_PENDING',
	UPDATE_FAIL: 'UPDATE_FAIL',

	SHOULD_SHOW_INTRO: 'SHOULD_SHOW_INTRO',

	FEED_PAGE_LENGTH: 20,

	PRE_AUTH_PROJECT_DATA: 'PRE_AUTH_PROJECT_DATA',

	ADDED: 'ADDED',

	DEMO_LOAD_EVENTS_SUCCESS: 'DEMO_LOAD_EVENTS_SUCCESS',

	FILTER_PHOTOS_SELECTED: 'FILTER_PHOTOS_SELECTED',

	REPLACE_SELECTED_PHOTOS: 'REPLACE_SELECTED_PHOTOS',

	ADD_PHOTO: 'ADD_PHOTO',

	TOGGLE_FETCHING_PHOTOS: 'TOGGLE_FETCHING_PHOTOS',

	LOAD_ORDERS: 'LOAD_ORDERS',
	LOAD_ORDERS_SUCCESS: 'LOAD_ORDERS_SUCCESS',
	LOAD_ORDERS_FAIL: 'LOAD_ORDERS_FAIL',

	LOAD_ORDER_DETAILS: 'LOAD_ORDER_DETAILS',
	LOAD_ORDER_DETAILS_SUCCESS: 'LOAD_ORDER_DETAILS_SUCCESS',
	LOAD_ORDER_DETAILS_FAIL: 'LOAD_ORDER_DETAILS_FAIL',

	LOAD_SHIPPING_INFO: 'LOAD_SHIPPING_INFO',
	LOAD_SHIPPING_INFO_SUCCESS: 'LOAD_SHIPPING_INFO_SUCCESS',
	LOAD_SHIPPING_INFO_FAIL: 'LOAD_SHIPPING_INFO_FAIL',

	LOAD_RETURNS: 'LOAD_RETURNS',
	LOAD_RETURNS_SUCCESS: 'LOAD_RETURNS_SUCCESS',
	LOAD_RETURNS_FAIL: 'LOAD_RETURNS_FAIL',

	LOAD_RETURN_DETAILS: 'LOAD_RETURN_DETAILS',
	LOAD_RETURN_DETAILS_SUCCESS: 'LOAD_RETURN_DETAILS_SUCCESS',
	LOAD_RETURN_DETAILS_FAIL: 'LOAD_RETURN_DETAILS_FAIL',

	// Returns reducer
	ORDER_TO_RETURN: 'ORDER_TO_RETURN',
	UPDATE_ITEM_IN_RETURN: 'UPDATE_ITEM_IN_RETURN',
	UPDATE_SHIPPING_METHODS: 'UPDATE_SHIPPING_METHODS',

	actions: {
		getProjects: 'get-projects',
		getEvents: 'get-events',
		signUserOut: 'sign-user-out',
	},

	user: {
		status: {
			unknown: 'unknown',
			anonymous: 'anonymous',
			authenticated: 'authenticated',
		},
	},
	EXPERT: '@BuildExpert',
	CLOUDINARY_URL: 'res.cloudinary.com',

	TERMS_OF_USE_URL: 'https://www.build.com/support/terms',
	SECURITY_AND_PRIVACY_URL: 'https://www.build.com/support/security',
	RETURNS_POLICY_URL: 'https://www.build.com/support/returns',

	ADD_PROJECT_ORDER_SUCCESS: 'ADD_PROJECT_ORDER_SUCCESS',

	ADD_PROJECT_ORDER_ERROR: 'ADD_PROJECT_ORDER_ERROR',

	ADD_PROJECT_ORDER: 'ADD_PROJECT_ORDER',

	TEMPLATE_ORDER: 'TEMPLATE_ORDER',
	TEMPLATE_SHIPPING_ESTIMATE: 'TEMPLATE_SHIPPING_ESTIMATE',

	GALLERY_GO_TO_INDEX: 'GALLERY_GO_TO_INDEX',

	TAP_RADIUS: 20,

	DOUBLE_TAP_DELAY: 300,

	// HalfPageListSelector heights
	HALF_HEIGHT: 'HALF',
	THREE_QUARTER_HEIGHT: 'THREE_QUARTERS',

	// constants for the tab bar
	MAIN: 'main',
	HOME: 'home',
	CART: 'cart',
	MORE: 'more',
	EXPERTS: 'experts',
	PROJECTS: 'projects',
	PROJECTSV2: 'projectsV2',
	LISTS: 'lists',

	// tab navigation for Checkout Screen
	ACTIVE: 'active',
	ENABLED: 'enabled',
	DISABLED: 'disabled',

	DEFAULT: 'default',

	FADE: 'fade',

	// Feature switches
	SET_FEATURE_STATE: 'SET_FEATURE_STATE',
	SET_FEATURE_WITH_EXPIRATION: 'SET_FEATURE_WITH_EXPIRATION',

	REFRESH_CURRENT_SCREEN: 'REFRESH_CURRENT_SCREEN',
	UNAUTHORIZED_ERROR: 'UNAUTHORIZED_ERROR',

	APP_LAUNCH_INFO: 'APP_LAUNCH_INFO',
	STORE_CUSTOMER_INFO: 'STORE_CUSTOMER_INFO',
	USER_LOGIN_STATUS: 'USER_LOGIN_STATUS',

	HIT_SLOP: {
		top: 14,
		left: 14,
		right: 14,
		bottom: 14,
	},

	STORE_NOTIFICATIONS_OPT_IN: 'STORE_NOTIFICATIONS_OPT_IN',
};

// DEV only constants
if (__DEV__) {
	constants.IMPERSONATOR_PASSWORD = 'IMPERSONATOR_PASSWORD';
}

module.exports = constants;
