'use strict';

const contentConstants = {
	LOAD_CONTENT: 'LOAD_CONTENT',
	LOAD_CONTENT_SUCCESS: 'LOAD_CONTENT_SUCCESS',
	LOAD_CONTENT_FAIL: 'LOAD_CONTENT_FAIL',

	LOAD_SHARED_PROMO_SUCCESS: 'LOAD_SHARED_PROMO_SUCCESS',
	LOAD_SHARED_PROMO_FAIL: 'LOAD_SHARED_PROMO_FAIL',

	LOAD_CONTENT_GROUP_SUCCESS: 'LOAD_CONTENT_GROUP_SUCCESS',
	LOAD_CONTENT_GROUP_FAIL: 'LOAD_CONTENT_GROUP_FAIL',

	LOAD_ROUTE_PAGE: 'LOAD_ROUTE_PAGE',
	LOAD_ROUTE_PAGE_SUCCESS: 'LOAD_ROUTE_PAGE_SUCCESS',
	LOAD_ROUTE_PAGE_FAIL: 'LOAD_ROUTE_PAGE_FAIL',

	LOAD_NAMED_SHARED_ITEM_SUCCESS: 'LOAD_NAMED_SHARED_ITEM_SUCCESS',
	LOAD_NAMED_SHARED_ITEM_FAIL: 'LOAD_NAMED_SHARED_ITEM_FAIL',

	CATEGORY: 'CATEGORY',
	ROUTE: 'ROUTE',
	ARTICLE: 'ARTICLE',
	SHARED: 'SHARED',

	INCLUDE_TYPES: {
		ARTICLE: 'article',
		CATEGORY: 'category',
		FAVORITE: 'favorite',
		PRODUCT: 'product',
		PROFILE: 'profile',
		TAG: 'tag',
		USER: 'user',
		VIDEO: 'video',
	},

};

module.exports = contentConstants;
