export const DELETE_PENDING = 'DELETE_PENDING';
export const DELETE_FAIL = 'DELETE_FAIL';

export const ADD_PENDING = 'ADD_PENDING';
export const ADD_FAIL = 'ADD_FAIL';

export const UPDATE_PENDING = 'UPDATE_PENDING';
export const UPDATE_FAIL = 'UPDATE_FAIL';

export const SHOULD_SHOW_INTRO = 'SHOULD_SHOW_INTRO';

export const FEED_PAGE_LENGTH = 20;

export const PRE_AUTH_PROJECT_DATA = 'PRE_AUTH_PROJECT_DATA';
