'use strict';

const favoritesConstants = {
	LOAD_CUSTOMER_FAVORITES: 'LOAD_CUSTOMER_FAVORITES',
	LOAD_CUSTOMER_FAVORITES_SUCCESS: 'LOAD_CUSTOMER_FAVORITES_SUCCESS',
	LOAD_CUSTOMER_FAVORITES_FAIL: 'LOAD_CUSTOMER_FAVORITES_FAIL',

	LOAD_FAVORITE_COMPOSITE_SUCCESS: 'LOAD_FAVORITE_COMPOSITE_SUCCESS',
	LOAD_FAVORITE_COMPOSITE_FAIL: 'LOAD_FAVORITE_COMPOSITE_FAIL',

	DELETE_FAVORITE_PRODUCT: 'DELETE_FAVORITE_PRODUCT',

	SAVE_FAVORITE_PRODUCT: 'SAVE_FAVORITE_PRODUCT',
	SAVE_FAVORITE_PRODUCT_SUCCESS: 'SAVE_FAVORITE_PRODUCT_SUCCESS',
	SAVE_FAVORITE_PRODUCT_FAIL: 'SAVE_FAVORITE_PRODUCT_FAIL',

	SAVE_PROJECT_FAVORITE_SUCCESS: 'SAVE_PROJECT_FAVORITE_SUCCESS',
	SAVE_PROJECT_FAVORITE_FAIL: 'SAVE_PROJECT_FAVORITE_FAIL',

	PROJECT_SAVE_FAVORITE_SUCCESS: 'PROJECT_SAVE_FAVORITE_SUCCESS',
	PROJECT_SAVE_FAVORITE_FAIL: 'PROJECT_SAVE_FAVORITE_FAIL',

	SAVE_NEW_FAVORITES: 'SAVE_NEW_FAVORITES',
	SAVE_NEW_FAVORITES_SUCCESS: 'SAVE_NEW_FAVORITES_SUCCESS',
	SAVE_FAVORITES_FAIL: 'SAVE_FAVORITES_FAIL',
	UPDATE_FAVORITES_SUCCESS: 'UPDATE_FAVORITES_SUCCESS',

	DELETE_FAVORITES: 'DELETE_FAVORITES',
	DELETE_FAVORITES_SUCCESS: 'DELETE_FAVORITES_SUCCESS',
	DELETE_FAVORITES_FAIL: 'DELETE_FAVORITES_FAIL',

	CLEAR_SAVE_ERROR: 'CLEAR_SAVE_ERROR',

	SET_SHOW_MODAL_PENDING: 'SET_SHOW_MODAL_PENDING',
};

module.exports = favoritesConstants;
