'use strict';

const layoutConstants = {

	// actions
	SET_COMPONENT_MEASUREMENTS: 'SET_COMPONENT_MEASUREMENTS',
	SET_TUTORIAL_MODE: 'SET_TUTORIAL_MODE',

	// components
	HOME_TAB: 'HOME_TAB',
	CART_TAB: 'CART_TAB',
	EXPERTS_TAB: 'EXPERTS_TAB',
	SEARCH_ICON: 'SEARCH_ICON',
	PROJECTS_BUTTON: 'PROJECTS_BUTTON',
	FAVORITES_BUTTON: 'FAVORITES_BUTTON',
	ORDERS_BUTTON: 'ORDERS_BUTTON',
	ACCOUNT_DETAILS_BUTTON: 'ACCOUNT_DETAILS_BUTTON',
	SHOPPING_LISTS: 'SHOPPING_LISTS',

};

module.exports = layoutConstants;
