
export default {
	START_LOOKBACK_RECORDING: 'START_LOOKBACK_RECORDING',
	STOP_LOOKBACK_RECORDING: 'STOP_LOOKBACK_RECORDING',
	RECORDING_STATUS_INACTIVE: 'RECORDING_STATUS_INACTIVE',
	RECORDING_STATUS_STOPPED: 'RECORDING_STATUS_STOPPED',
	RECORDING_STATUS_RECORDING: 'RECORDING_STATUS_RECORDING',
};
