export const GET_NOTIFICATION_SETTINGS_SUCCESS = 'GET_NOTIFICATION_SETTINGS_SUCCESS';
export const GET_NOTIFICATION_SETTINGS_FAIL = 'GET_NOTIFICATION_SETTINGS_FAIL';

export const SAVE_GUEST_NOTIFICATION_SETTINGS_SUCCESS = 'SAVE_GUEST_NOTIFICATION_SETTINGS_SUCCESS';
export const SAVE_NOTIFICATION_SETTINGS = 'SAVE_NOTIFICATION_SETTINGS';
export const SAVE_NOTIFICATION_SETTINGS_SUCCESS = 'SAVE_NOTIFICATION_SETTINGS_SUCCESS';
export const SAVE_NOTIFICATION_SETTINGS_FAIL = 'SAVE_NOTIFICATION_SETTINGS_FAIL';

export const UPDATE_NOTIFICATION_COUNT = 'UPDATE_NOTIFICATION_COUNT';
export const MARK_NOTIFICATION_READ = 'MARK_NOTIFICATION_READ';
export const NOTIFICATION_SETTINGS_HAVE_BEEN_UPDATED = 'NOTIFICATION_SETTINGS_HAVE_BEEN_UPDATED';
export const LOAD_NOTIFICATIONS = 'LOAD_NOTIFICATIONS';
export const LOAD_NOTIFICATIONS_SUCCESS = 'LOAD_NOTIFICATIONS_SUCCESS';
export const LOAD_NOTIFICATIONS_FAILED = 'LOAD_NOTIFICATIONS_FAILED';
export const SAVE_NOTIFICATION_SUCCESS = 'SAVE_NOTIFICATION_SUCCESS';
export const CLEAR_NOTIFICATIONS_DATA = 'CLEAR_NOTIFICATIONS_DATA';
export const MARK_NOTIFICATIONS_ACKNOWLEDGED = 'MARK_NOTIFICATIONS_ACKNOWLEDGED';

export const ORDER_NOTIFICATIONS = ['ORDER', 'RETURN', 'TRACKING'];

export const GUEST_NOTIFICATIONS_SETTINGS = 'GUEST_NOTIFICATIONS_SETTINGS';

export const ALLOW_NOTIFICATIONS_SUCCESS = 'ALLOW_NOTIFICATIONS_SUCCESS';
export const ALLOW_NOTIFICATIONS_FAILED = 'ALLOW_NOTIFICATIONS_FAILED';
