export const SET_PRODUCT_SPEC_FILTER = 'SET_PRODUCT_SPEC_FILTER';
export const UPDATE_SQUARE_FOOTAGE = 'UPDATE_SQUARE_FOOTAGE';
export const REVIEW_SORT_TEXT = {
	MOST_HELPFUL: 'Most Helpful',
	NEWEST_TO_OLDEST: 'Newest to Oldest',
	OLDEST_TO_NEWEST: 'Oldest to Newest',
	HIGH_TO_LOW: 'High to Low Rating',
	LOW_TO_HIGH: 'Low to High Rating',
};
export const REVIEW_SORT_OPTIONS = [
	'MOST_HELPFUL',
	'NEWEST_TO_OLDEST',
	'OLDEST_TO_NEWEST',
	'HIGH_TO_LOW',
	'LOW_TO_HIGH',
];
export const REVIEW_SORT_CRITERIA = {
	MOST_HELPFUL: 'Helpfulness:desc',
	NEWEST_TO_OLDEST: 'SubmissionTime:desc',
	OLDEST_TO_NEWEST: 'SubmissionTime:asc',
	HIGH_TO_LOW: 'Rating:desc',
	LOW_TO_HIGH: 'Rating:asc',
};
export const RECEIVE_PRODUCT_REVIEWS_SUCCESS = 'RECEIVE_PRODUCT_REVIEWS_SUCCESS';
export const RECEIVE_PRODUCT_REVIEWS_FAILURE = 'RECEIVE_PRODUCT_REVIEWS_FAILURE';
export const REVIEWS_RESET_FAILURE = 'REVIEWS_RESET_FAILURE';
export const CLEAR_REVIEWS = 'CLEAR_REVIEWS';
export const SET_QUESTION_AND_ANSWER_FILTER = 'SET_QUESTION_AND_ANSWER_FILTER';
export const RADIO_OPTION = 'RADIO';
export const CHECK_BOX_OPTION = 'CHECKBOX';
export const NO_THANK_YOU = 'NO THANK YOU';
export const I_DONT_NEED_THIS = 'I DON\'T NEED THIS';
export const GET_PRODUCT_SPECS_SUCCESS = 'GET_PRODUCT_SPECS_SUCCESS';
export const GET_PRODUCT_SPECS_FAIL = 'GET_PRODUCT_SPECS_FAIL';
export const SAVE_LAST_VIEWED_PRODUCT_COMPOSITE_ID = 'SAVE_LAST_VIEWED_PRODUCT_COMPOSITE_ID';
export const CONSUMER_PRICEBOOK_ID = 1;
export const RECEIVE_PRODUCT_ROOT_CATEGORY = 'RECEIVE_PRODUCT_ROOT_CATEGORY';
export const GET_AR_PRODUCTS_SUCCESS = 'GET_AR_PRODUCTS_SUCCESS';
