export default {
	30: 'Architect',
	31: 'Electrician',
	32: 'Facilities Manager/Handyman',
	33: 'General Contractor/Remodeler',
	34: 'Government',
	35: 'Hospitality Lodging',
	36: 'HVAC Contractor',
	37: 'Interior Designers Decorators',
	38: 'Kitchen Bath Dealer/Designer',
	39: 'Landscape Contractor/Architect/Designer',
	40: 'Non-Profit Organization',
	41: 'Plumbing Contractor',
	42: 'Property Manager/Investor',
	43: 'Reseller/Retailer',
	44: 'Custom Builder',
	45: 'Other',
};
