export const UPDATE_IS_FETCHING_PROJECT_DATA = 'UPDATE_IS_FETCHING_PROJECT_DATA';
export const UPDATE_SHOW_PROJECT_EVENTS = 'UPDATE_SHOW_PROJECT_EVENTS';
export const UPDATE_ACTIVE_PROJECT_EVENTS_FILTER = 'UPDATE_ACTIVE_PROJECT_EVENTS_FILTER';
export const PROJECT_UPDATE_IS_REFRESHING = 'PROJECT_UPDATE_IS_REFRESHING';
