export const UPDATE_PROJECTS_FILTER = 'UPDATE_PROJECTS_FILTER';
export const PROJECTS_SEARCH_FILTER = 'PROJECTS_SEARCH_FILTER';

export const MIN_PROJECTS_FOR_SEARCH = 5;

export const ADD_ITEM_TO_SHOPPING_LIST_SUCCESS = 'ADD_ITEM_TO_SHOPPING_LIST_SUCCESS';
export const ADD_ITEM_TO_SHOPPING_LIST_FAIL = 'ADD_ITEM_TO_SHOPPING_LIST_FAIL';

export const SAVING_SHOPPING_LIST = 'SAVING_SHOPPING_LIST';
export const SAVE_SHOPPING_LIST_SUCCESS = 'SAVE_SHOPPING_LIST_SUCCESS';
export const SAVE_SHOPPING_LIST_FAIL = 'SAVE_SHOPPING_LIST_FAIL';

export const CREATE_PROJECT_WITH_DEFAULT_GROUP_SUCCESS = 'CREATE_PROJECT_WITH_DEFAULT_GROUP_SUCCESS';
export const CREATE_PROJECT_WITH_DEFAULT_GROUP_FAIL = 'CREATE_PROJECT_WITH_DEFAULT_GROUP_FAIL';

export const ITEM_ADDED_TO_PROJECT = 'ITEM_ADDED_TO_PROJECT';

export const RESET_SHOPPING_LISTS_EDITING_FLAG = 'RESET_SHOPPING_LISTS_EDITING_FLAG';
export const RESET_LOADING_FLAG = 'RESET_LOADING_FLAG';

export const REMOVE_ITEM_FROM_SHOPPING_LIST_SUCCESS = 'REMOVE_ITEM_FROM_SHOPPING_LIST_SUCCESS';
export const REMOVE_ITEM_FROM_SHOPPING_LIST_FAIL = 'REMOVE_ITEM_FROM_SHOPPING_LIST_FAIL';

export const DELETE_GROUP_SUCCESS = 'DELETE_GROUP_SUCCESS';
