'use strict';

const searchConstants = {

	SEARCH_SUCCESS: 'SEARCH_SUCCESS',
	SEARCH_SUCCESS_ONLY_FACETS: 'SEARCH_SUCCESS_ONLY_FACETS',
	SEARCH_FAIL: 'SEARCH_FAIL',

	SEARCH_LIST: 'SEARCH_LIST',
	SEARCH_GRID: 'SEARCH_GRID',
	SEARCH_GALLERY: 'SEARCH_GALLERY',
	SET_SORT_OPTION: 'SET_SORT_OPTION',
	SORT_OPTIONS: [
		'PRICE_HIGH',
		'PRICE_LOW',
		'SCORE',
		'FAVORITE',
		'RATING',
	],
	SORT_TEXT: {
		PRICE_HIGH: 'Price (High to Low)',
		PRICE_LOW: 'Price (Low to High)',
		SCORE: 'Best Selling',
		FAVORITE: 'Times Favorited',
		RATING: 'Highest Rated',
	},

	START_LOADING: 'START_LOADING',
	CLEAR_FACETS: 'CLEAR_FACETS',
	APPLY_SELECTED_FACETS: 'APPLY_SELECTED_FACETS',
	UPDATE_SELECTED_FACETS: 'UPDATE_SELECTED_FACETS',

	TYPEAHEAD: 'TYPEAHEAD',
	CYCLE_VIEW_STYLE: 'CYCLE_VIEW_STYLE',
	VIEW_STYLE_LOADED: 'VIEW_STYLE_LOADED',

	TYPEAHEAD_MAX_RESULTS: 5,

	SET_NULL_SEARCH_RESULT: 'SET_NULL_SEARCH_RESULT',
};

module.exports = searchConstants;
