export const RESET_SINGLE_EVENT_DATA = 'RESET_SINGLE_EVENT_DATA';
export const LOAD_SINGLE_EVENT_FAIL = 'LOAD_SINGLE_EVENT_FAIL';
export const LOAD_SINGLE_EVENT_SUCCESS = 'LOAD_SINGLE_EVENT_SUCCESS';

export const SINGLE_EVENT_SAVE_COMMENT = 'SINGLE_EVENT_SAVE_COMMENT';
export const SINGLE_EVENT_SAVE_COMMENT_SUCCESS = 'SINGLE_EVENT_SAVE_COMMENT_SUCCESS';
export const SINGLE_EVENT_SAVE_COMMENT_FAIL = 'SINGLE_EVENT_SAVE_COMMENT_FAIL';
