export const SOCIAL_LOGIN_PROMPT_CREDS = 'SOCIAL_LOGIN_PROMPT_CREDS';
export const SOCIAL_GET_CLIENT_DATA = 'SOCIAL_GET_CLIENT_DATA';
export const SOCIAL_LINK_USER = 'SOCIAL_LINK_USER';
export const SOCIAL_LINK_USER_ERROR = 'SOCIAL_LINK_USER_ERROR';
export const DID_LOGIN_WITH_SOCIAL = 'DID_LOGIN_WITH_SOCIAL';
export const SOCIAL_LOGIN_TYPE = 'SOCIAL_LOGIN_TYPE';
