export const GET_RELATED_UPSELL_PRODUCTS = 'GET_RELATED_UPSELL_PRODUCTS';
export const RESET_RELATED_UPSELL_PRODUCTS = 'RESET_RELATED_UPSELL_PRODUCTS';
export const SET_SELECTED_UPSELL_FINISH = 'SET_SELECTED_UPSELL_FINISH';
export const SET_SELECTED_UPSELL_MODEL = 'SET_SELECTED_UPSELL_MODEL';
